wandb_version: 1

desc:
  desc: null
  value: Finetuning MSRVTT prima prova
batch-size:
  desc: null
  value: 32
ngpus:
  desc: null
  value: 4
architecture:
  desc: null
  value: VAST
dataset:
  desc: null
  value: MSRVTT
epochs:
  desc: null
  value: 3
_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.17.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1726521123
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 4
      - 16
      - 23
      - 42
      4: 3.9.19
      5: 0.17.8
      8:
      - 5
      13: linux-x86_64
